### ISSUE TITLE
Testing on iOS 5.x

### ISSUE THREAD

**Issue by matth3wga0** [benlodotcom/BLWebSocketsServer#1]
I'm wrapping libwebsockets for my project, then I found your wrapper, it seems that you haven't tested on iOS 5.x.

Latest libwebsockets doesn't support iOS 5.x since UIWebView on iOS 5.x is using an older draft which libwebsockets has deprecated.

**Comment by benlodotcom** [comment]
Hi mgplus,

Did you have a chance to test it on iOS5 or are you assuming it won't work ? Also BLWebSocketsServer doesn't have to be used exclusively with a UIWebView as a client.

**Comment by matth3wga0** [comment]
I have no idea which version of libwebsockets you're using, but I'm sure yours isn't up to date. Last time I clone from the git, it need **cmake** to get the missing **config.h** which is required.

I tried to copy your libwebsockets to my project, and add "LWS_NO_DAEMONIZE" to C Flags to pass the compiler, but it crashed at launching.

You can check out my copy here, https://github.com/mgplus/libwebsockets

**Comment by benlodotcom** [comment]
Mine is indeed not the head in the git repository. Have you tried compiling my repo with the iOS5 SDK ?

**Comment by matth3wga0** [comment]
Sorry, I can't, it seems that you're using storyboard
