### ISSUE TITLE
Last socket connected does not work

### ISSUE THREAD

**Issue by bdkjones** [benlodotcom/BLWebSocketsServer#3]
Hi Ben,

I've integrated BLWebSocketsServer into a Cocoa app on Mac OS 10.8.4. When I use the -pushToAll: method, it fails to work for the _most recently added_ socket. So, when I have only one client socket open, it does not work. But as soon as I open a second client socket (say, by loading the HTML page, which I'm serving locally over Mamp) the first socket client starts receiving the messages. Then, if I add a 3rd client (by opening the same html page on my iPad), both the first two clients start receiving messages but the most recent socket (the iPad) does not.

I'm wondering if this is a bug, or if I'm doing something wrong.

**Comment by bdkjones** [comment]
I should note: the socket opens correctly on each device! I added an alert() call the onOpen handler and every device (including the latest socket I open) shows this alert. However, the latest device fails to receive any messages from the -pushAll method.

**Comment by bdkjones** [comment]
Nevermind; I found the issue. 

You're using ARC, but didn't specify that in the project overview. Turning on the -fobjc-arc flag for your two .m files solves the problem. I recommend adding that to the readme, since not everyone uses ARC.

**Comment by benlodotcom** [comment]
Thanks for pointing out the omission in the Readme, I added a note about ARC.
