### ISSUE TITLE
-pushToAll sends dual messages

### ISSUE THREAD

**Issue by bdkjones** [benlodotcom/BLWebSocketsServer#5]
I've got BLWebSocketsServer set up normally and I have one "client" connected to the server. I'm encoding an NSString as NSData and then using the `-pushToAll:` method to simply send that string to the client on the other side of the socket. The client simply runs an 'alert()' to display the sent message.

The trouble is that every time I send a message, the client receives it TWICE. So I stuck an NSLog statement in this section of BLWebSocketsServer.m:

```
case LWS_CALLBACK_SERVER_WRITEABLE: {
    NSData *message = [sharedInstance.asyncMessageQueue messageForUserWithId:*session_id];
    NSLog(@"Writing: %@", [[NSString alloc] initWithData:message encoding:NSUTF8StringEncoding]);

    write_data_websockets(message, wsi);
    break;
    }
```

And sure enough, I see two "Writing: ..." messages in my log every time I call -pushToAll once. (I have a log statement in that method as well, verifying that it is called only once.)

Any advice on how to combat this? I have a feeling something is mixed up with the enqueue/dequeue stuff so that the messageCount is off, or the messages aren't properly removed.

**Comment by bdkjones** [comment]
Also: I haven't ruled out the possibility that I'm doing something wrong, but I'm pretty sure I've got everything set correctly. Took me about 4 hours to realize it was the server sending dual messages rather than a bug in my javascript on the client side. (I originally started with a fairly complex script and finally got so frustrated, I backed it off to a simple, "Let's just alert the damn message from the server and see if it's even coming through correctly.")

**Comment by benlodotcom** [comment]
I cannot reproduce the issue with my demo code.

Could you replace the `- (NSData *)messageForUserWithId:(int)userId` method in `BLAsyncMessageQueue` with the following code and give me the output of the two NSLogs ?

``` objc
- (NSData *)messageForUserWithId:(int)userId {
    NSData *message;
    @synchronized(self) {
        NSLog(@"BEFORE DEQUEUE %d %@", userId, self.usersMessageQueues[[NSNumber numberWithInt:userId]]);
       message = [self.usersMessageQueues[[NSNumber numberWithInt:userId]] dequeue];
        self.messagesCount--;
        NSLog(@"AFTER DEQUEUE %d %@", userId, self.usersMessageQueues[[NSNumber numberWithInt:userId]]);
    }
    return message;
}
```

**Comment by bdkjones** [comment]
For the record, this was related to ARC. 

Enabling the correct ARC flag for the file solved the problem.
